[toolchain]
channel = "nightly-2026-06-04"
targets = [
	"armv7r-none-eabi",
	"armv7r-none-eabihf",
	"armv7a-none-eabi",
	"armv7a-none-eabihf",
	"thumbv7r-none-eabi",
	"thumbv7r-none-eabihf",
	"thumbv7a-none-eabi",
	"thumbv7a-none-eabihf",
]
components = ["rust-src", "clippy", "rustfmt"]
